version: '3.1'
services:
 jenkins:
  restart: always
  privileged: true
  user: root
  container_name: jenkins
  image: kamalyes/jenkins:2.387.3-lts-jdk11-slim
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8080"]
    interval: 6s
    timeout: 5s
    retries: 10
  volumes:
   - /root/.ssh:/root/.ssh
   - /opt/jenkins/:/var/jenkins_home
   - /opt/jenkins/workspace/:/root/.jenkins/workspace
   - /var/run/docker.sock:/var/run/docker.sock
   - /usr/bin/docker:/usr/bin/docker
   - /usr/bin/buildctl:/usr/local/bin/buildctl
   - /usr/local/go:/usr/local/go
   - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
   - /usr/local/gradle-7.3.3:/usr/local/gradle-7.3.3
   - /usr/local/gradle-7.6:/usr/local/gradle-7.6
   - /usr/local/jdk11.0.1:/usr/local/jdk11.0.1
   - /usr/local/jdk1.8.0_141:/usr/local/jdk1.8.0_141
   - /usr/local/node-v16.19.1-linux-x64:/usr/local/node-v16.19.1-linux-x64
   - /usr/local/python3:/usr/local/python3
   - /usr/local/android-sdk-linux:/usr/local/android-sdk-linux
  ports:
   - 18080:8080
   - 15001:50000
